<?php
/**
 * @package     Windwalker.Framework
 * @subpackage  AKHelper
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */


// No direct access
defined('_JEXEC') or die;


class AKHelperFields
{
	/*
	 * function setFieldTable
	 * @param $table
	 */
	
	public static function setFieldTable($table, $attrs = null, $option = array())
	{
		$field_type = $table->get('field_type', 'text') ;
		if(!is_array($attrs)){
			$attrs = $_REQUEST['attrs'] ;
		}
		
		// Check is table have all needed column
		// ==================================================================
		self::checkTable($table);
		
		
		
		// Filter Attrs
		// ==================================================================
		$attrs = self::filterFields($field_type, $attrs) ;
		
		
		
		// Convert Name to uppercase and safe ID
		// ==================================================================
		$name = JArrayHelper::getValue($attrs, 'name' ) ;
		$name = self::filterName($name);
		$attrs['name'] = $name;
		
		// Set Name as Field ID
		if(isset($table->name)){
			$table->set('name', $name );
		}
		
		
		// Remove empty options
		// ==================================================================
		foreach( $attrs['options']['value'] as $k => $val ):
			if(!$attrs['options']['value'][$k] && !$attrs['options']['text'][$k]){
				unset($attrs['options']['value'][$k]);
				unset($attrs['options']['text'][$k]);
			}
		endforeach;
		
		
		
		// Build Element
		// ==================================================================
		$table->element = self::buildElement( $field_type , $attrs);
		$table->name 	= $name ;
		$table->attrs	= json_encode($attrs) ;
	}
	
	
	/*
	 * function buildElement
	 * @param 
	 */
	
	public static function buildElement($field_type = 'text', $attrs = null, $option = array())
	{
		$node_name = $option['node_name'] ? $option['node_name'] : 'field' ;
		$field_type = $field_type ? $field_type : 'text' ;
		
		if(!is_array($attrs)){
			$attrs = $_REQUEST['attrs'] ;
			$attrs = self::filterFields($field_type, $attrs) ;
		}
		
		if(!is_array($attrs)) {
			return '<'.$node_name.'/>' ;
		}
		
		
		// Rebuild options
		// ================================================================
		$new_options = array();
		foreach( $attrs['options']['value'] as $key => $option ):
			$new_options[$key]['value'] = $attrs['options']['value'][$key] ;
			$new_options[$key]['text'] = $attrs['options']['text'][$key] ;
		endforeach;
		$attrs['options'] = $new_options ;
		
		
		$element = '' ;
		$options = array();
		
		
		
		// Build Field Attrs
		// ================================================================
		
		// set type in attrs
		$attrs['type'] = $field_type;
		
		// set default
		if(is_array($attrs['default'])){
			$attrs['default'] = implode(',', $attrs['default']);
		}
		
		
		// start buliding attrs and options
		foreach( $attrs as $key => $attr ):
			if($key == 'options' && is_array($attr)) {
				
				// Bulid options
				foreach( $attr as $key => $opt ):
					if(!trim($opt['value'])) continue;
					$value 	= addslashes( trim($opt['value']) );
					$text	= htmlspecialchars( addslashes( trim($opt['text']) ) );
					$options[] = "\t<option value=\"{$value}\">{$text}</option>\n" ;
				endforeach;
				
			}else{
				// Build attributes
				if(!trim($attr)) continue;
				$attr = trim($attr) ;
				$attr = htmlspecialchars( addslashes($attr) );
				$element .= "\t{$key}=\"{$attr}\"\n" ;
			}
		endforeach;
		
		
		
		// Build Element
		// ================================================================
		if(count($options) < 0){
			$element = "<{$node_name}\n{$element}/>" ;
		}else{
			$options = implode('', $options) ;
			$element = "<{$node_name}\n{$element}>\n{$options}</{$node_name}>" ;
		}
		
		
		return $element;
	}
	
	
	
	/*
	 * function parseAttrs
	 * @param $attrs
	 */
	
	public static function parseAttrs($attrs)
	{
		if(!$attrs) return false;
		
		$array = (array)json_decode($attrs);
		
		// Save options to new var
		// ================================================================
		$options = null ;
		if(isset($array['options'])) {
			$array['options'] = (array) $array['options'] ;
			$options = $array['options'];
		}
		
		
		// Rebuild Options
		// ==================================================================
		if($options) {
			$array['options'] = array();
			$i = 0 ;
			foreach( $options['value'] as $key => $option ):
				$array['options'][$i]['text'] = (string)$options['text'][$i] ;
				$array['options'][$i]['value'] = (string)$option ;
				$i++;
			endforeach;
		}
		
		return $array;
	}
	
	
	
	/*
	 * function parseElement
	 * @param $element
	 */
	
	public static function parseElement($element)
	{
		if(!$element) return false;
		
		$xml = JFactory::getXML($element, false);
		$attrs = $xml->attributes();
		
		$array = array();
		
		
		
		// Save Attrs
		// ================================================================
		foreach( $attrs as $key => $attr ):
			$array[$key] = (string)$attr ;
		endforeach;
		
		
		
		// Save options
		// ================================================================
		$options = $xml->option ;
		
		if($options) {
			$i = 0 ;
			foreach( $options as $key => $option ):
				$array['options'][$i]['text'] = (string)$option ;
				$array['options'][$i]['value'] = (string)$option['value'] ;
				$i++;
			endforeach;
		}
		AK::show($array);
		return $array;
	}
	
	
	
	/*
	 * function filterFields
	 * @param $data
	 */
	
	public static function filterFields($field_type = 'text', $data = array())
	{
		// Clean text
		// ==================================================================
		foreach( $data as $key => &$val ):
			if($key == 'options' || is_array($val)) continue;
			
			$val = trim($val);
		endforeach;
		
		
		// Filter Text
		// ==================================================================
		JForm::addFormPath(AKPATH_FORM.'/forms/attr');
		$form = JForm::getInstance( 'fields', $field_type, array(), false, false );
		
		$data = $form->filter($data) ;
		
		return $data;
	}
	
	
	
	/*
	 * function filterName
	 * @param $name
	 */
	
	public static function filterName($name)
	{
		// Make Name as safe ID
		// ==================================================================
		$name = JFilterOutput::stringURLSafe($name);
		$name = str_replace('-', '_', $name) ;
		$name = strtoupper($name) ;
		
		return $name ;
	}
	
	
	/*
	 * function checkTable
	 * @param $table
	 */
	
	public static function checkTable($table)
	{
		// Needed columns
		$needed = array(
			'title',
			'name',
			'field_type',
			'element',
			'attrs'
		);
		
		
		
		// Check columns
		// ==================================================================
		$lack = array();
		
		foreach( $needed as $needed ):
			if(!property_exists($table, $needed)) {
				$lack[] = $needed ;
			}
		endforeach;
		
		// Raise Error
		if(count($lack) > 0) {
			$message = "Table {$table->getTableName()} need columns: ".implode(', ', $lack) ;
			JError::raiseError( 500, $message) ;
		}
	}
}