<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_userxtd
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;



// Init some API objects
// ================================================================================
$app 	= JFactory::getApplication() ;
$date 	= JFactory::getDate( 'now' , JFactory::getConfig()->get('offset') ) ;
$doc 	= JFactory::getDocument();
$uri 	= JFactory::getURI() ;
$user	= JFactory::getUser();
$userId	= $user->get('id');



// List Control
// ================================================================================
$listOrder	= $this->state->get('list.ordering');
$listDirn	= $this->state->get('list.direction');
$canOrder	= $user->authorise('core.edit.state', 'com_userxtd');
$saveOrder	= $listOrder == 'a.ordering' || ($listOrder == 'a.lft' && $listDirn == 'asc');
$trashed	= $this->state->get('filter.published') == -2 ? true : false;
$nested		= $this->state->get('items.nested') ;
$orderCol 	= $nested ? 'a.lft' : 'a.ordering' ;
$show_root	= JRequest::getVar('show_root') ;

?>

<!-- List Table -->
<table class="table table-striped adminlist" id="itemList">
	<thead>
		<tr>
			
			<th width="1%">
				<input type="checkbox" name="checkall-toggle" value="" onclick="Joomla.checkAll(this)" />
			</th>
			
			<th>
				<?php echo JHtml::_('grid.sort',  'JGLOBAL_TITLE', 'a.title', $listDirn, $listOrder); ?>
			</th>
			
			
			
			<th width="1%" class="nowrap">
				<?php echo JHtml::_('grid.sort',  'JGRID_HEADING_ID', 'a.id', $listDirn, $listOrder); ?>
			</th>

		</tr>
	</thead>
	<tfoot>
		<tr>
			<td colspan="15">
				<div class="pull-left">
					<?php echo $this->pagination->getListFooter(); ?>
				</div>
				
				<?php if( JVERSION >= 3 ): ?>
				<!-- Limit Box -->
				<div class="btn-group pull-right hidden-phone">
					<label for="limit" class="element-invisible"><?php echo JText::_('JFIELD_PLG_SEARCH_SEARCHLIMIT_DESC');?></label>
					<?php echo $this->pagination->getLimitBox(); ?>
				</div>
				<?php endif; ?>
			</td>
		</tr>
	</tfoot>
	<tbody>
	<?php foreach ($this->items as $i => $item) :
		
		$item = new JObject($item);
		
		$ordering	= ($listOrder == $orderCol);
		$canEdit	= $user->authorise('core.edit',			'com_userxtd.user.'.$item->a_id);
		$canCheckin	= $user->authorise('core.manage',		'com_userxtd.user.'.$item->a_id) || $item->a_checked_out == $userId || $item->a_checked_out == 0;
		$canChange	= $user->authorise('core.edit.state',	'com_userxtd.user.'.$item->a_id) && $canCheckin;
		$canEditOwn = $user->authorise('core.edit.own',		'com_userxtd.user.'.$item->a_id) && $item->a_id == $userId;

		?>
		<tr class="row<?php echo $i % 2; ?>">
		
			<td class="center">
				<?php echo JHtml::_('grid.id', $i, $item->a_id); ?>
			</td>
			
			<td class="n/owrap has-context">
				<!-- Nested dashs -->
				<?php if( $nested ): ?>
				<div class="pull-left fltlft">
					<?php $offset = $show_root ? 0 : 1 ; ?>
					<?php echo str_repeat('<span class="gi">&mdash;</span>', $item->a_level - $offset) ; ?>
				</div>
				<?php endif; ?>
				
				<div class="pull-left fltlft">
				
				
				<!-- Checkout -->
				<?php if ($item->get('a_checked_out')) : ?>
					<?php echo JHtml::_('jgrid.checkedout', $i, $item->get('a_checked_out'), $item->get('a_checked_out_time'), 'users.', $canCheckin); ?>
				<?php endif; ?>
				
				
				<!-- Title -->
				<?php if ($canEdit || $canEditOwn) : ?>
					<a href="<?php echo JRoute::_('index.php?option=com_userxtd&task=user.edit&id='.$item->a_id); ?>">
						<?php echo $item->get('a_title'); ?>
					</a>
				<?php else: ?>
					<?php echo $item->get('a_title'); ?>
				<?php endif; ?>
				
			</td>
			

			<td class="center">
				<span
					<?php if( $nested ): ?>
					class="hasTip" title="<?php echo $item->a_lft.'-'.$item->a_rgt; ?>"
					<?php endif; ?>
				><?php echo (int) $item->get('a_id'); ?></span>
			</td>

		</tr>
		<?php endforeach; ?>
	</tbody>
</table>