<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_userxtd
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

include_once AKPATH_COMPONENT.'/modeladmin.php' ;

/**
 * Userxtd model.
 */
class UserxtdModelField extends AKModelAdmin
{
	/**
	 * @var		string	The prefix to use with controller messages.
	 * @since	1.6
	 */
	protected 	$text_prefix = 'COM_USERXTD';
	
	public 		$component = 'userxtd' ;
	public 		$item_name = 'field' ;
	public 		$list_name = 'fields' ;
	
	
	
	/**
     * Constructor.
     *
     * @param    array    An optional associative array of configuration settings.
     * @see        JController
     * @since    1.6
     */
    public function __construct($config = array())
    {
        parent::__construct($config);
		
		$this->setState('CCKEngine.enabled', true);
    }
	
	

	/**
	 * Method to get the record form.
	 *
	 * @param	array	$data		An optional array of data for the form to interogate.
	 * @param	boolean	$loadData	True if the form is to load its own data (default case), false if not.
	 * @return	JForm	A JForm object on success, false on failure
	 * @since	1.6
	 */
	public function getForm($data = array(), $loadData = true)
	{
		$form = parent::getForm($data, $loadData) ;
		
		return $form ;
	}
	
	
	/*
	 * function getFields
	 * @param 
	 */
	
	public function getFields()
	{
		$fields = parent::getFields();
		
		return $fields ;
	}
	
	

	/**
	 * Method to get the data that should be injected in the form.
	 *
	 * @return	mixed	The data for the form.
	 * @since	1.6
	 */
	protected function loadFormData()
	{
		$retain = JRequest::getVar('retain', 0) ;
		
		$data 	= (array) parent::loadFormData();
		$attrs 	= JFactory::getApplication()->getUserState("{$this->option}.edit.field.fields", array());
		
		if($attrs) {
			$data['attrs'] = json_encode($attrs) ;
			
			foreach( $data as &$d ):
				if(is_array($d)) {
					$d['attrs'] = json_encode($attrs) ;
				}
			endforeach;
		}
		
		// Set Change Field Type Retain Data
		if($retain) {
			$data 	= JRequest::getVar('jform') ;
			$attrs 	= json_encode(JRequest::getVar('attrs')) ;
			
			$data2 = array() ;
			foreach( $data as $key => &$val ):
				/*
				if(is_array($val)) {
					$data2 = array_merge($data2, $val) ;
				}else{
					$data2[$key] = $val ;
				}
				*/
				$val['attrs'] = $attrs;
			endforeach;
			
			//$data = $data2 ;
			
			$data['attrs'] = $attrs;
		}
		
		return $data ;
	}

	
	
	/**
	 * Method to get a single record.
	 *
	 * @param	integer	The id of the primary key.
	 *
	 * @return	mixed	Object on success, false on failure.
	 * @since	1.6
	 */
	public function getItem($pk = null)
	{
		if($item = parent::getItem($pk)){
			
			
			
			return $item ;	
		}

		return false;
	}
	
	
	/**
	 * Method to auto-populate the model state.
	 *
	 * Note. Calling getState in this method will result in recursion.
	 *
	 * @since	1.6
	 */
	protected function populateState()
	{
		parent::populateState();
	}
	
	
	
	/**
     * Method to allow derived classes to preprocess the form.
     *
     * @param   JForm   $form   A JForm object.
     * @param   mixed   $data   The data expected for the form.
     * @param   string  $group  The name of the plugin group to import (defaults to "content").
     *
     * @return  void 
     *
     * @see     JFormField
     * @since   11.1
     * @throws  Exception if there is an error in the form event.
     */
    protected function preprocessForm(JForm $form, $data, $group = 'content')
	{
		return parent::preprocessForm($form, $data, $group);
	}
	
	

	/**
	 * Prepare and sanitise the table prior to saving.
	 *
	 * @since	1.6
	 */
	protected function prepareTable(&$table)
	{
		$db = JFactory::getDbo();
		$q = $db->getQuery(true) ;
		
		if (!$table->ordering) {
			$q->select("MAX(ordering)")
				->from("#__userxtd_fields")
				->where('catid='.$table->catid)
				;
			$db->setQuery($q);
			$max = $db->loadResult();
			$table->ordering = $max+1;
		}
		
		parent::prepareTable($table);
	}
	
}