<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_userxtd
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

$doc 	= JFactory::getDocument();
$app 	= JFactory::getApplication();
$lang 	= JFactory::getLanguage();
$params = JComponentHelper::getParams('com_userxtd') ;



// Include Helpers
// ========================================================================

// Core init, it can use by module, plugin or other component.
include_once JPath::clean( JPATH_ADMINISTRATOR . "/components/com_userxtd/includes/core.php" ) ;

// Set default option to path helper, then AKHelperPath will helpe us get admin path.
AKHelper::_('path.setOption', 'com_userxtd') ;


// Some useful settings
if( $app->isSite() ){
	
	// Include Admin language as global language.
	$lang->load('', JPATH_ADMINISTRATOR);
	$lang->load('com_userxtd', JPATH_COMPONENT_ADMINISTRATOR );
	UserxtdHelper::_('lang.loadAll', $lang->getTag());
	
	// Include com_users Language
	UXHelper::_('lang.loadLanguage', 'com_users', 'site');
	UXHelper::_('lang.loadLanguage', 'com_users', 'admin');
	
	
	// Include Bootstrap
	if($params->get('UserInfo_IncludeCSS_Component', 1)) {
		UXHelper::_('include.bootstrap', true, true) ;
		$doc->addStyleSheet('components/com_userxtd/includes/css/userxtd-component.css');
	}
	
	
	// Include Joomla! admin css
	UserxtdHelper::_('include.sortedStyle', 'includes/css');
	
	
	// set Base to fix toolbar anchor bug
	$doc->setBase( JFactory::getURI()->toString() );
	
}else{
	UserxtdHelper::_('lang.loadAll', $lang->getTag());
	UserxtdHelper::_('include.sortedStyle', 'includes/css');
	
	// Include com_users Language
	UXHelper::_('lang.loadLanguage', 'com_users', 'site');
	UXHelper::_('lang.loadLanguage', 'com_users', 'admin');
}


// Detect version
UserxtdHelper::_('plugin.attachPlugins');

// Enable CCK Engine
JForm::addFieldPath(AKPATH_FORM.'/fields/cck');

// Debug
define('AKDEBUG', UserxtdHelper::_('system.getConfig', 'system.debug')) ;
