<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_userxtd
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

include_once AKPATH_COMPONENT.'/viewlist.php' ;

/**
 * View class for a list of Userxtd.
 */
class UserxtdViewUsers extends AKViewList
{
	/**
	 * @var		string	The prefix to use with controller messages.
	 * @since	1.6
	 */
	protected 	$text_prefix = 'COM_USERXTD';
	protected 	$items;
	protected 	$pagination;
	protected 	$state;
	
	public		$option 	= 'com_userxtd' ;
	public		$list_name 	= 'users' ;
	public		$item_name 	= 'user' ;
	public		$sort_fields ;

	
	
	/**
	 * Display the view
	 */
	public function display($tpl = null)
	{
		$app = JFactory::getApplication() ;
		
		$this->fields		= $this->get('Fields');
		$this->state		= $this->get('State');
		$this->items		= $this->get('Items');
		$this->pagination	= $this->get('Pagination');
		$this->filter		= $this->get('Filter');
		$this->keys			= $this->state->get('profileKeys');
		$this->filteredFields	= $this->state->get('filteredFields');
		

		// Check for errors.
		if (count($errors = $this->get('Errors'))) {
			JError::raiseError(500, implode("\n", $errors));
			return false;
		}
		
		
		parent::displayWithPanel($tpl);
	}

	
	
	/**
	 * Add the page title and toolbar.
	 *
	 * @since	1.6
	 */
	protected function addToolbar()
	{
		// Set title.
		AKToolBarHelper::title( JText::_($this->text_prefix.'_TITLE_USERS_LIST'), 'article.png');
		
		$canDo	= AKHelper::getActions($this->option);
		
		if ($canDo->get('core.admin')) {
			AKToolBarHelper::preferences($this->option);
		}
		
		UXHelper::_('userConfigButton') ;
		//parent::addToolbar();
	}
	
	
	/**
	 * Returns an array of fields the table can be sorted by
	 *
	 * @return  array  Array containing the field name to sort by as the key and display text as value
	 *
	 * @since   3.0
	 */
	protected function getSortFields()
	{
		$ordering_key = $this->state->get('items.nested') ? 'a.lft' : 'a.ordering' ;
		
		$this->sort_fields = array(
			'a.name' 		=> JText::_('COM_USERS_HEADING_NAME'),
			'a.username' 			=> JText::_('JGLOBAL_USERNAME')
		);
		
		foreach( $this->fields as $field ):
			$this->sort_fields[$field->name] = $field->title ;
		endforeach;
		
		return $this->sort_fields ;
	}
	
	
}
