<?php
/**
 * @package     Windwalker.Framework
 * @subpackage  class
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

JForm::addFieldPath( AKPATH_FORM.'/fields');

/**
 * Supports an HTML select list of categories
 */
class JFormFieldFields extends JFormField
{
	/**
	 * The form field type.
	 *
	 * @var		string
	 * @since	1.6
	 */
	public $type = 'Fields';
	
	public $value ;
	
	public $name ;
	
	
	
	/**
	 * Method to get the field input markup.
	 *
	 * @return	string	The field input markup.
	 * @since	1.6
	 */
	public function getInput()
	{
		$element 	= $this->element ;
		
		$this->addFieldJs();
		
		// ParseValue
		$data = AKHelper::_('fields.parseElement', $this->value);
		
		$type 	= JRequest::getVar('field_type', 'text') ;
		
		JForm::addFormPath( AKPATH_FORM.'/forms/attr' );
		$form = JForm::getInstance( 'fields', $type, array('control' => 'attrs'), false, false );
		$form->bind($data);
		JRequest::setVar('field_default', $data['default'], 'method', true) ;
		
		$fields = $form->getFieldset('attrs');
		//AK::show($fields);
		
		$html = '' ;
		foreach( $fields as $field ):
			$html .= '<div class="control-group">' ;
			$html .= '	<div class="control-label">'.$field->getLabel().'</div>' ;
			$html .= '			<div class="controls">'.$field->getInput().'</div>' ;
			$html .= '</div>' ;
		endforeach;
		
		
		return  $html;

	}
	
	
	/*
	 * function addFieldJs
	 * @param 
	 */
	
	public function addFieldJs()
	{
		$doc = JFactory::getDocument();
		$akpath_js = JPath::clean(AKPATH_ASSETS) ;
		$js_url = str_replace( JPATH_ROOT, '', $akpath_js ).'/js/fields.js' ;
		$js_url = trim($js_url, '/') ;
		$js_url = JRoute::_('../'.$js_url);
		
		$doc->addScript($js_url);
	}
}