<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_userxtd
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

include_once AKPATH_COMPONENT.'/viewlist.php' ;

/**
 * View class for a list of Userxtd.
 */
class UserxtdViewProfiles extends AKViewList
{
	/**
	 * @var		string	The prefix to use with controller messages.
	 * @since	1.6
	 */
	protected 	$text_prefix = 'COM_USERXTD';
	protected 	$items;
	protected 	$pagination;
	protected 	$state;
	
	public		$option 	= 'com_userxtd' ;
	public		$list_name 	= 'profiles' ;
	public		$item_name 	= 'profile' ;
	public		$sort_fields ;

	
	
	/**
	 * Display the view
	 */
	public function display($tpl = null)
	{
		$app = JFactory::getApplication() ;
		
		$this->state		= $this->get('State');
		$this->items		= $this->get('Items');
		$this->pagination	= $this->get('Pagination');
		$this->filter		= $this->get('Filter');

		// Check for errors.
		if (count($errors = $this->get('Errors'))) {
			JError::raiseError(500, implode("\n", $errors));
			return false;
		}
		
		parent::displayWithPanel($tpl);
	}

	
	
	/**
	 * Add the page title and toolbar.
	 *
	 * @since	1.6
	 */
	protected function addToolbar()
	{
		// Set title.
		AKToolBarHelper::title( ucfirst($this->getName()) . ' ' . JText::_($this->text_prefix.'_TITLE_LIST'), 'article.png');
		
		$state	= $this->get('State');
		$canDo	= AKHelper::getActions($this->option);
		$user 	= JFactory::getUser() ;
		$filter_state 	= $this->state->get('filter') ;
		
        // Get the toolbar object instance
		$bar = JToolBar::getInstance('toolbar');
       
		
		// Toolbar Buttons
		// ========================================================================
		if ($canDo->get('core.create') || (count($user->getAuthorisedCategories($this->option, 'core.create'))) > 0 ) {
			JToolBarHelper::addNew( $this->item_name.'.add');
		}

		if ($canDo->get('core.edit')) {
			JToolBarHelper::editList( $this->item_name.'.edit');
		}

		if ($canDo->get('core.edit.state')) {
			JToolBarHelper::divider();
			JToolBarHelper::publish( $this->list_name.'.publish', 'JTOOLBAR_PUBLISH', true);
			JToolBarHelper::unpublish( $this->list_name.'.unpublish', 'JTOOLBAR_UNPUBLISH', true);
			JToolbarHelper::checkin($this->list_name.'.checkin');
			
			if($this->state->get('items.nested')){
				JToolBarHelper::custom($this->list_name.'.rebuild', 'refresh.png', 'refresh_f2.png', 'JTOOLBAR_REBUILD', false);
			}
			
			JToolBarHelper::divider();
		}
		
		if ($canDo->get('core.delete')) {
			JToolbarHelper::deleteList('Are you sure?', $this->list_name.'.delete');
		}
		
		// Add a batch modal button
		if ($user->authorise('core.edit') && JVERSION >= 3)
		{
			AKToolbarHelper::modal( 'JTOOLBAR_BATCH', 'batchModal');
		}
		
		if ($canDo->get('core.admin')) {
			AKToolBarHelper::preferences($this->option);
		}
	}
	
	
	/**
	 * Returns an array of fields the table can be sorted by
	 *
	 * @return  array  Array containing the field name to sort by as the key and display text as value
	 *
	 * @since   3.0
	 */
	protected function getSortFields()
	{
		$ordering_key = $this->state->get('items.nested') ? 'a.lft' : 'a.ordering' ;
		
		$this->sort_fields = array(
			$ordering_key 		=> JText::_('JGRID_HEADING_ORDERING'),
			'a.published' 		=> JText::_('JPUBLISHED'),
			'a.title' 			=> JText::_('JGLOBAL_TITLE'),
			'b.title' 			=> JText::_('JCATEGORY'),
			'd.title' 			=> JText::_('JGRID_HEADING_ACCESS'),
			'a.created_by' 		=> JText::_('JAUTHOR'),
			'e.title' 			=> JText::_('JGRID_HEADING_LANGUAGE'),
			'a.created' 		=> JText::_('JDATE'),
			'a.id' 				=> JText::_('JGRID_HEADING_ID')
		);
		
		//return $this->sort_fields ;
	}
	
	
}
