<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_userxtd
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

include_once __DIR__ . '/../src/init.php';

/**
 * Class UserxtdHelperFieldshow
 *
 * @since 1.0
 */
class UserxtdHelperFieldshow
{
	/**
	 * showImage
	 *
	 * @param mixed $value
	 *
	 * @return  string
	 */
	public static function showImage($value)
	{
		if($value)
		{
			$thumb = new \Windwalker\Image\Thumb(null, 'com_userxtd');

			$value = $thumb->resize($value, 300, 300);

			return JHtml::image($value, 'UserXTD image');
		}
	}
}
