<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_userxtd
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

JHtml::_('behavior.framework');
//UserxtdHelper::_('include.bootstrap', true, true);

// Create shortcuts to some parameters.
$params		= $this->item->params;
$profile	= $this->profiles;
$canEdit	= $this->item->params->get('access-edit');
$user		= JFactory::getUser();
$item 		= $this->item ;
$uri 		= JFactory::getURI() ;
$isSelf		= ( $user->id == $item->id ) ;

// Set Profile Data
$data 		= $profile->getDataForShow( 'profile', array('profile' => $item->profiles) );
$fieldsets	= $profile->getFieldsets( 'profile' );


$exclude_fields = array() ;
$exclude_fields[] = $avatar_field 	= $params->get('UserInfo_ImageField', 'BASIC_AVATAR');
$exclude_fields[] = $title_field 	= $params->get('UserInfo_TitleField', 'name');
$exclude_fields[] = $about_field 	= $params->get('UserInfo_AboutField', 'BASIC_ABOUT');

$this->exclude_fields = $exclude_fields;
$show_cats = $this->params->get('show_categories', '*') ;
?>

<script type="text/javascript">
	jQuery('.dropdown-toggle').dropdown();
</script>
<form action="<?php echo JRoute::_('index.php?option=com_userxtd&view=user'); ?>" method="post" name="adminForm" id="adminForm">

	<div id="userxtd-wrap" class="container-fluid users<?php echo $this->get('pageclass_sfx');?>">
		<div id="userxtd-wrap-inner">
			
			<div class="user-item item">
				<div class="user-item-inner">
					
					
					
					<!-- afterDisplayTitle -->
					<!-- ============================================================================= -->
					<?php echo $this->item->event->afterDisplayTitle; ?>
					<!-- ============================================================================= -->
					<!-- afterDisplayTitle -->
					
					
					<!-- beforeDisplayContent -->
					<!-- ============================================================================= -->
					<?php echo $this->item->event->beforeDisplayUser; ?>
					<!-- ============================================================================= -->
					<!-- beforeDisplayContent -->
					
					
					<div class="row-fluid">
						<div class="profile-avatar span4">
								
							<div class="profile-avatar-inner">
								<?php $avatar = $item->get($avatar_field); ?>
								<img src="<?php echo $avatar ? $avatar : JURI::root().'components/com_userxtd/images/default_avatar.png'; ?>" class="img-polaroid" alt="UserXTD Avatar <?php echo $user->username; ?>" />
							</div>
							
						</div>	
					
					
					
						<!-- Info -->
						<!-- ============================================================================= -->
						<div class="profile-info span8">
							<div class="profile-info-inner">
								
								<?php if ($canEdit) : ?>
								<!-- Edit -->
								<!-- ============================================================================= -->
								<div class="edit-icon btn-toolbar fltrt pull-right">
									<div class="btn-group">
										<?php echo JHtml::_( 'link', JRoute::_('index.php?option=com_userxtd&task=user.edit&id='.$item->id.'&return='.UserxtdHelper::_('uri.base64', 'encode', $uri->toString())) , '<i class="icon-edit"></i> '.JText::_('JTOOLBAR_EDIT'), array( 'class' => 'btn btn-small' ) ); ?>
										<!--
										<button class="btn btn-small dropdown-toggle" data-toggle="dropdown">
											<span class="caret"></span>
										</button>
										
										<ul class="dropdown-menu">
											<li>
												<a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb<?php echo $item->id; ?>','users.publish')" title="啟用"><?php echo JText::_('JTOOLBAR_ENABLE'); ?></a>
											</li>
											<li>
												<a class="jgrid" href="javascript:void(0);" onclick="return listItemTask('cb<?php echo $item->id; ?>','users.unpublish')" title="停用"><?php echo JText::_('JTOOLBAR_DISABLE'); ?></a>
											</li>
										</ul>
										-->
									  </div>
									
								</div>
								<div style="display: none;">
									<?php echo JHtml::_('grid.id', $item->id, $item->id); ?>
								</div>
								<!-- ============================================================================= -->
								<!-- Edit End -->
								<?php endif; ?>	
								
								
								<div class="heading">
									<h2><?php echo $item->get('link_titles') ? JHtml::_('link', $item->link, $item->name) : $item->name ?></h2>
									<div class="user-name">( <?php echo $item->username; ?> )</div>
								</div>
								
								<hr />
								
								<div class="about">
									<?php echo $item->get($about_field); ?>
								</div>
							</div>	
						
						</div>
					</div>
					<!-- ============================================================================= -->
					<!-- Info -->
					
					
					
					<!-- Heading -->
					<!-- ============================================================================= -->
					
					<!-- ============================================================================= -->
					<!-- Heading -->
					
					
					
					<!-- Content -->
					<!-- ============================================================================= -->
					<div class="profile-content">
						<div class="profile-content-inner row-fluid">
							
							<div class="span12">
								
								<?php
								$this->data		= $data ;
								foreach( $fieldsets as $fieldset ):
									
									if( $show_cats != '*'
									   && !in_array( str_replace('userxtd-cat-', '', $fieldset->name) ,$show_cats) )
									{
										continue;
									}
									
									$this->fieldset = $fieldset ;
									echo $this->loadTemplate('profile');
									
								endforeach; ?>
								
							</div>
							
						</div>
					</div>
					<!-- ============================================================================= -->
					<!-- Content End -->
					
					<?php if( $isSelf ): ?>
					<hr />
					<dl class="dl-horizontal">
									
						<!--Register Date-->
						<dt>
							<?php echo JText::_('COM_USERS_PROFILE_REGISTERED_DATE_LABEL'); ?>
						</dt>
						<dd>
							<?php echo JFactory::getDate( $item->get('registerDate') , JFactory::getConfig()->get('offset') )->format('Y-m-d') ; ?>
						</dd>
						
						
						<!--Last Visit Date-->
						<dt>
							<?php echo JText::_('COM_USERS_PROFILE_LAST_VISITED_DATE_LABEL'); ?>
						</dt>
						<dd>
							<?php echo JFactory::getDate( $item->get('lastvisitDate') , JFactory::getConfig()->get('offset') )->format('Y-m-d') ; ?>
						</dd>
						
					</dl>
					<?php endif; ?>
					
					<!-- afterDisplayContent -->
					<!-- ============================================================================= -->
					<?php echo $this->item->event->afterDisplayUser; ?>
					<!-- ============================================================================= -->
					<!-- afterDisplayContent -->
					
					
					
				</div>
			</div>
			
		</div>
	</div>
	
	<div>
		<input type="hidden" name="task" value="" />
		<input type="hidden" name="boxchecked" value="0" />
		<input type="hidden" name="return" value="<?php echo base64_encode($uri->toString()); ?>" />
		<?php echo JHtml::_('form.token'); ?>
	</div>
</form>		
