<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_userxtd
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

// Create shortcuts to some parameters.
$params		= $this->item->params;
$fieldset 	= $this->fieldset ;


$avatar_field 	= $params->get('UserInfo_ImageField', 'BASIC_AVATAR');
$title_field 	= $params->get('UserInfo_TitleField', 'name');
$about_field 	= $params->get('UserInfo_AboutField', 'BASIC_ABOUT');
?>
<fieldset>
	<legend>
		<?php echo $fieldset->label; ?>
	</legend>
	
	<dl class="dl-horizontal">
	<?php
	
	$fields = $this->profiles->getFieldset($fieldset->name) ;
	
	?>
	
	<?php foreach( $fields as $field ): ?>
		
		<?php if( in_array( $field->fieldname, $this->exclude_fields ) ) continue; ?>
		
		<dt>
			<?php echo $field->title; ?>
		</dt>
		<dd>
			<?php echo $this->data[$field->fieldname]; ?>
		</dd>
	<?php endforeach; ?>
	</dl>
</fieldset>

